// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace Application
{
	public static class RCUtilities
	{

		/*
		 * checks if a number is within a given range. Works for floats 
		 */
		static bool CheckRange(this float num, float min, float max)
		{
			return num > min && num < max;
		}
	}
}

